apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
patches:
  - path: patches.yaml
images:
  - name: yny.ocir.io/NAMESPACE/cergy2026/backend
    newName: yny.ocir.io/axx4mcvilido/cergy2026/backend
    newTag: latest
  - name: yny.ocir.io/NAMESPACE/cergy2026/frontend
    newName: yny.ocir.io/axx4mcvilido/cergy2026/frontend
    newTag: latest
